// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htegorovrqorrfydgadn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0ZWdvcm92cnFvcnJmeWRnYWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTE3MjgsImV4cCI6MjA2NzQ4NzcyOH0.5KLbxKXljrEA5exT3q7ZFg4nCnOGI-BhCQJwnZNTYEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});